### ISSUE TITLE
Enclosed middle for right plate?

### ISSUE THREAD

**Issue by jwlawrence** [keebio/fourier-case#1]
Just curious as to why there is an enclosed middle for the left plate, but not the right. Is this by design or are we simply missing the file for the right plate? Thanks for posting these case files, keep up the great work.

**Comment by nooges** [comment]
I hadn't found a good way to enclose the middle because of one of the stab legs prevents complete closure. But now that you mention it, I could add a notch to compensate for that area.

**Comment by jwlawrence** [comment]
That would probably look pretty cool actually. I would submit a PR, but I don't know how to 3D model :)

**Comment by nooges** [comment]
I'm not particularly good either, I just fool around with Tinkercad.

**Comment by nooges** [comment]
@jwlawrence Alright, I've designed an enclosed middle for the right half, tested it out, and posted the file.
